### ISSUE TITLE
Windows-incompatibe file names?

### ISSUE THREAD

**Issue by ArtemGr** [KomodoPlatform/developer-docs#112]
I've a problem checking out the repository on Windows:

<img width="677" alt="Annotation 2019-07-30 015132" src="https://user-images.githubusercontent.com/41847/62088077-c0100c00-b26c-11e9-86e5-f137e7d94058.png">

```
error: unable to create file docs/.vuepress/public/KMD_Brand_Assets/Horizontal/Black/Icon?: Invalid argument
error: unable to create file docs/.vuepress/public/KMD_Brand_Assets/Horizontal/Dark/Icon?: Invalid argument
```

Looks like a carriage return (%0D) sneaked into the file names (https://github.com/KomodoPlatform/developer-docs/blob/master/docs/.vuepress/public/KMD_Brand_Assets/Horizontal/Black/Icon%0D).

I suspect it's a bug, and it prevents me and possibly other developers from working normally with the docs.

**Comment by gcharang** [comment]
commit: https://github.com/KomodoPlatform/developer-docs/pull/124/commits/30208cf4a0b39e0b43cd276895813e2a52b3e966 solves the issue, once PR: https://github.com/KomodoPlatform/developer-docs/pull/124 is merged
