### ISSUE TITLE
yarn docs:dev will fail if until algolia-key.sh is run.

### ISSUE THREAD

**Issue by artemii235** [KomodoPlatform/developer-docs#119]
`algolia-key.sh` creates `./docs/.vuepress/algolia-secret.js` file, I get `Error: Cannot find module './algolia-secret.js'` since it's required by config.js. This part is not mentioned in Readme.
@gcharang could you please advice on this since it seems that you added the algolia in https://github.com/KomodoPlatform/developer-docs/commit/c08e8a4217965638877f2091b4df08ed507d8a87

**Comment by gcharang** [comment]
sorry for the oversight @artemii235 	
a fresh clone after the PR: https://github.com/KomodoPlatform/developer-docs/pull/124 is merged should fix the issue
