### ISSUE TITLE
dice.html not showing up on the Antara Modules list 

### ISSUE THREAD

**Issue by NOCTLJRNE** [KomodoPlatform/developer-docs#133]
![AntaraDoc](https://user-images.githubusercontent.com/13896688/67050005-cdd08180-f137-11e9-8818-eaae2b2b7116.JPG)

**Comment by siddhartha-crypto** [comment]
This was done at the request of some of the highly engaged users and developers in the DICE community. Please reach out to @Alrighttt for more information.
