### ISSUE TITLE
Feature request: Define path to MM2.json as runtime param

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/developer-docs#134]
It would be handy to be able to reference an MM2.json file located in a specific folder, or by a different name to allow quick changing of the wallet seed used at launch.

E.g.
 ```
./mm2 conf=/home/user/folder/mm2_primary.json
./mm2 conf=/home/user/folder/mm2_secondary.json
```

**Comment by artemii235** [comment]
@smk762 Thanks for creating the issue, it's nice to have indeed.

**Comment by artemii235** [comment]
@smk762 Could you move it to https://github.com/KomodoPlatform/atomicDEX-API/issues please? I feel like developer-docs repo is not a right place for AtomicDEX-API feature requests.

**Comment by smk762** [comment]
lol, sorry followed wrong link!

**Comment by smk762** [comment]
Moved to https://github.com/KomodoPlatform/atomicDEX-API/issues/562
