### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by barbierir** [KomodoPlatform/developer-docs#140]
At the tutorial page: 
https://developers.komodoplatform.com/basic-docs/antara/antara-tutorials/beginner-series-part-1.html

clicking at the end on the "Link to the next tutorial in this series" takes to:
https://developers.komodoplatform.com/basic-docs/antara/antara-tutorials/overview-of-development-on-komodo-part-2.html  

that is a dead link btw, I suppose it should instead take to: 
https://developers.komodoplatform.com/basic-docs/antara/antara-tutorials/beginner-series-part-2.html

**Comment by siddhartha-crypto** [comment]
Thanks, sorry I missed this. Fixed now.
