### ISSUE TITLE
Tables with arguments and responses, remove "structure

### ISSUE THREAD

**Issue by imylomylo** [KomodoPlatform/developer-docs#17]

**Comment by imylomylo** [comment]
Just needs a sed command run over all docs to replace `| Structure |` with `| Name |`
Some instances of `|     Structure     |` may exist so replacing any amount of whitespace between "pipe and (sS)" and "e and pipe" will probably work across all pages.

**Comment by siddhartha-crypto** [comment]
This is a good suggestion. 

I'm going to save it for our upcoming hire to take care of, as it's a good way to get acquainted with the files.
