### ISSUE TITLE
Few packages mentioned in the liquidity provider tutorial are outdated

### ISSUE THREAD

**Issue by damascene** [KomodoPlatform/developer-docs#273]
I was trying to follow the liquidity provider tutorial but I found the command specified in the guide is outdated. 
I was suggesting installing old packages:
`sudo apt-get install build-essential git jq llvm-3.9-dev libclang-3.9-dev clang-3.9 cmake libssl-dev pkg-config` 
Many of them where missing from Ubuntu 20.04, this worked for me:
`sudo apt-get install build-essential git jq llvm-dev libclang-dev clang cmake libssl-dev pkg-config`

https://developers.komodoplatform.com/basic-docs/atomicdex/atomicdex-tutorials/how-to-become-a-liquidity-provider.html#installing-dependencies

**Comment by gcharang** [comment]
thanks! merged https://github.com/KomodoPlatform/developer-docs/pull/274
