### ISSUE TITLE
docker yarn docs:dev requires yarn add -D vuepress

### ISSUE THREAD

**Issue by imylomylo** [KomodoPlatform/developer-docs#3]
For some reason, the docker image required me to `yarn add -D vuepress` to get it to work.

**Comment by gcharang** [comment]
Yeah. The yarn.lock is being copied over after the installation. Will correct the instructions.

**Comment by gcharang** [comment]
THis commit: https://github.com/KomodoPlatform/developer-docs/commit/cab81ec5ec2b45139ca5dd01712020fd04f3afda fixes it.
