### ISSUE TITLE
Add rpc_password policy and allow_weak_password field to API docs.

### ISSUE THREAD

**Issue by artemii235** [KomodoPlatform/developer-docs#324]
We're currently applying stricter rules to the `rpc_password` set by users, which might be turned off using the `allow_weak_password` flag. Related PR in the API (not merged yet): https://github.com/KomodoPlatform/atomicDEX-API/pull/1144/files

**Comment by smk762** [comment]
Done in https://github.com/KomodoPlatform/developer-docs/pull/326
