### ISSUE TITLE
Document save_in_history argument of buy/sell/setprice.

### ISSUE THREAD

**Issue by artemii235** [KomodoPlatform/developer-docs#327]
It defines whether to save all information about order updates in a separate DB folder/table. It has a boolean type and the default value is "true".

**Comment by smk762** [comment]
Is this for saving to swap_json file of a local sqlite db? Or is json file done regardless, this just also saves in db?

**Comment by artemii235** [comment]
@smk762 If `save_in_history` is `true` the following happens:
1. When an order is created or updated, its short record is saved to SQLite DB in addition to a json file.
2. When the order is canceled/fully matched, its json is saved into the `DB/PUBKEY_HASH/ORDERS/MY/HISTORY` directory.

It is related to orders only. This flag doesn't affect the storage of swaps data.

**Comment by smk762** [comment]
Thanks -  just to be clear: if `false` is it stored at all anywhere?

**Comment by artemii235** [comment]
In the `false` case, it will be available in the `order_status` as the `changes_history` field. Once the order is deleted, the `changes_history` will be deleted too.
