### ISSUE TITLE
Document paid_from_trading_volume field of the trade_preimage fees response.

### ISSUE THREAD

**Issue by artemii235** [KomodoPlatform/developer-docs#330]
It indicates whether the fee will be deducted from the trading volume during the swap. For example, it is deducted from the payment amount to spend/refund UTXO HTLC (paid_from_trading_volume: true), but ETH users require ETH on their balance upfront for the same actions (paid_from_trading_volume: false).

**Comment by smk762** [comment]
I'm seeing this response for a KMD/DGB trade, which indicates `false` can occur in cases where gas is not involved. I assume this is because maker side does not pay fee?
```
  "result": {
    "base_coin_fee": {
      "coin": "KMD",
      "amount": "0.00001",
      "amount_fraction": {
        "numer": "1",
        "denom": "100000"
      },
      "amount_rat": [ [ 1, [ 1 ] ], [ 1, [ 100000 ] ] ],
      "paid_from_trading_vol": false
    },
    "rel_coin_fee": {
      "coin": "DGB",
      "amount": "0.00030782",
      "amount_fraction": {
        "numer": "15391",
        "denom": "50000000"
      },
      "amount_rat": [ [ 1, [ 15391 ] ], [ 1, [ 50000000 ] ] ],
      "paid_from_trading_vol": true
    },```

**Comment by artemii235** [comment]
The HTLC output will have the same amount as trading vol, and the maker pays an additional `0.00001` miner fee to broadcast his swap transaction. When he spends DGB HTLC, the `0.00030782` miner fee will be deducted from the payment output so `paid_from_trading_vol` is true.

**Comment by smk762** [comment]
Done in https://github.com/KomodoPlatform/developer-docs/pull/331
