### ISSUE TITLE
Documentation: Bitcoin should be changed to Litecoin

### ISSUE THREAD

**Issue by maxfossen** [KomodoPlatform/developer-docs#334]
The documentation claims security by BTC but it has been changed by LTC.

**Comment by gcharang** [comment]
thanks for raising the issue. I have found BTC mentioned re:dPoW in https://developers.komodoplatform.com/basic-docs/start-here/core-technology-discussions/delayed-proof-of-work.html and https://developers.komodoplatform.com/basic-docs/start-here/core-technology-discussions/initial-dex-offering.html

@maxfossen can you please let me know if you found any other places that need to be corrected?
