### ISSUE TITLE
Create guide on asset adding into desktop GUI

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/developer-docs#337]
@smk762 when you'll have a chance please make a guide/instruction on how to add assets into desktop GUI: coins repo part + files which needs to be changed, logo and etc

**Comment by smk762** [comment]
Drafted the GUI part of this in https://github.com/KomodoPlatform/developer-docs/blob/smk-dev/docs/basic-docs/atomicdex/atomicdex-desktop/add-coin-to-atomicdex-desktop.md (WIP)

**Comment by gcharang** [comment]
merged
