### ISSUE TITLE
Negative confirmations of tx and KMD didn't deliver

### ISSUE THREAD

**Issue by The-Mike007** [KomodoPlatform/developer-docs#375]
Hello. I have an issue. I sent 1000 KMD to my Ledger wallet address and seems my tx is stuck. 
by listtransactions got such result:
<img width="562" alt="list" src="https://user-images.githubusercontent.com/25158276/176895198-76dc7d39-9b07-469a-9580-996067b422f8.png">

`{
    "account": "",
    "address": "RMn6xtRV1zutpKeiT5jsSFcRKCCZXcpi1s",
    "category": "send",
    "amount": -1000.00000000,
    "vout": 1,
    "fee": 4.27883438,
    "rawconfirmations": -1,
    "confirmations": -1,
    "txid": "6227a0eac12c1fc2608b1abded6729e8af869d63538441223ce3df036437d209",
    "walletconflicts": [
    ],
    "time": 1656625651,
    "timereceived": 1656625651,
    "vjoinsplit": [
    ],
    "size": 244
  }
`

Any KMD explorer don't see this TX and KMD on my Ledger wallet is zero.
Also KMD didn't return back to my sending wallet balance.

It's first time when I'm facing such situation.
Can anybody help me with it? 
How to return KMD back to my balance? 
Or resend this tx somehow?

**Comment by cipig** [comment]
tx was removed from mempool and not mined
from the debug.log of one of my nodes:
`2022-06-30 21:47:31 ERROR: AcceptToMemoryPool: komodo_validate_interest failed txid.6227a0eac12c1fc2608b1abded6729e8af869d63538441223ce3df036437d209`
komodod does account for this though, so balance should be back to normal
how did you send those KMD? which wallet?

**Comment by The-Mike007** [comment]
> tx was removed from mempool and not mined from the debug.log of one of my nodes: `2022-06-30 21:47:31 ERROR: AcceptToMemoryPool: komodo_validate_interest failed txid.6227a0eac12c1fc2608b1abded6729e8af869d63538441223ce3df036437d209` komodod does account for this though, so balance should be back to normal how did you send those KMD? which wallet?

update to the last version and `-rescan` helped me.
Coins are back.
