### ISSUE TITLE
Add interactive atomicdex method examples

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/developer-docs#381]
now that we have a postman collection, it would be nice to use something similar to codepen / swagger to allow the user to create a request from a form, see the equivalent curl command, and click a button to get a response from one of the playground nodes.

@gcharang I think this should be possible via https://github.com/amplia-iiot/vuepress-theme-openapi but if you know of any better method please let me know.

**Comment by gcharang** [comment]
afaik, https://github.com/amplia-iiot/vuepress-theme-openapi won't be directly useful. we can take inspiration from there and implement an extension to the default theme (template and js).

the first issue I see is to write a parser and manipulator function in js that understands the rules described by @shamardy here https://github.com/KomodoPlatform/developer-docs/issues/362#issuecomment-1101299392

**Comment by smk762** [comment]
closing, migrated issue to new repo
