### ISSUE TITLE
Add docs for activating ZHTLC coins

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/developer-docs#391]
```
curl --url "http://127.0.0.1:7783" --data "
{
    \"userpass\": \"${userpass}\",
    \"method\": \"init_z_coin\",
    \"mmrpc\": \"2.0\",
    \"params\": {
        \"ticker\": \"ARRR\",
        \"activation_params\": {
            \"mode\": {
                \"rpc\": \"Light\",
                \"rpc_data\": {
                    \"electrum_servers\": [{\"url\":\"pirate.sirseven.me:10032\"}],
                    \"light_wallet_d_servers\": [\"http://pirate.sirseven.me:443\"]
                }
            }
        }
    }
}"
```

```
curl --url "http://127.0.0.1:7783" --data "
{
    \"userpass\": \"${userpass}\",
    \"method\": \"init_z_coin_status\",
    \"mmrpc\": \"2.0\",
    \"params\": {
        \"task_id\": $1
    }
}"
```
Possible Error responses: https://github.com/KomodoPlatform/atomicDEX-API/blob/28749e38e22137c64a025d348bae22db4e33d3c3/mm2src/coins_activation/src/standalone_coin/init_standalone_coin_error.rs#L16

`init_zcoin_status` response varies depending which stage it is at.
Zcash params must be locally downloaded to activate ZHTLC coins.

**Comment by sergeyboyko0791** [comment]
In one of my PRs, I changed the names of some methods including `init_zcoin`, `init_zcoin_status` and `init_zcoin_user_aciton`.
Basically, I just added namespaces to combine some methods into groups, especially `init_<METHOD><_ACTION>` into `task::<METHOD>::<ACTION>`.
Thus,
`init_zcoin` => `task::enable_zcoin::init`
`init_zcoin_status` => `task::enable_zcoin::status`
`init_zcoin_user_action` => `task::enable_zcoin::user_action`

https://github.com/KomodoPlatform/atomicDEX-API/blob/30ca312332d30c8ded4ea36bf91bf2d0256cff36/mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs#L193-L245

**Comment by smk762** [comment]
> In one of my PRs [KomodoPlatform/atomicDEX-API#1405](https://github.com/KomodoPlatform/atomicDEX-API/pull/1405), I changed the names of some methods including `init_zcoin`, `init_zcoin_status` and `init_zcoin_user_aciton`. Basically, I just added namespaces to combine some methods into groups, especially `init_<METHOD><_ACTION>` into `task::<METHOD>::<ACTION>`. Thus, `init_zcoin` => `task::enable_zcoin::init` `init_zcoin_status` => `task::enable_zcoin::status` `init_zcoin_user_action` => `task::enable_zcoin::user_action`
> 
> Changelog: [link](https://github.com/KomodoPlatform/atomicDEX-API/blob/30ca312332d30c8ded4ea36bf91bf2d0256cff36/mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs#L226-L229)
> 
> Also I added `task::enable_zcoin::cancel` to gracefully cancel the coin activation task.

Please excuse my confusion. The highlighted portion in the linked changelog only has `z_coin` under "native_only_methods". 
I assume parameters and request structure is unchanged? In sending the request, would it now look like the below?

```
curl --url "http://127.0.0.1:7783" --data "
{
    \"userpass\": \"${userpass}\",
    \"method\": \"task::enable_zcoin::init\",
    \"mmrpc\": \"2.0\",
    \"params\": {
       ...
    }
}"

**Comment by sergeyboyko0791** [comment]
Sorry, I chose the wrong lines of code, thanks for the correction.
> The highlighted portion in the linked changelog only has z_coin under "native_only_methods".

Exactly the same.
> I assume parameters and request structure is unchanged?

Only those methods that lead to spawning tasks, i.e. those functions whose status needs to be polled.
Currently, all such methods are related to HW integration and initializing Zcoin.
> And how far does this renaming extend to other v2 RPCs?

**Comment by smk762** [comment]
Updated methods:

```
#!/bin/bash
source userpass
curl --url "http://127.0.0.1:7783" --data "
{
    \"userpass\": \"$userpass\",
    \"method\": \"task::enable_z_coin::init\",
    \"mmrpc\": \"2.0\",
    \"params\": {
        \"ticker\": \"ZOMBIE\",
        \"activation_params\": {
            \"mode\": {
                \"rpc\": \"Light\",
                \"rpc_data\": {
                    \"electrum_servers\": [{\"url\":\"zombie.sirseven.me:10033\"}],
                    \"light_wallet_d_servers\": [\"http://zombie.sirseven.me:443\"]
                }
            }
        }
    }
}"
echo

#!/bin/bash
source userpass
curl --url "http://127.0.0.1:7783" --data "
{
    \"userpass\": \"${userpass}\",
    \"method\": \"task::enable_z_coin::status\",
    \"mmrpc\": \"2.0\",
    \"params\": {
        \"task_id\": $1
    }
}"
echo


#!/bin/bash
source userpass
curl --url "http://127.0.0.1:7783" --data "
{
    \"userpass\": \"${userpass}\",
    \"method\": \"task::enable_z_coin::cancel\",
    \"mmrpc\": \"2.0\",
    \"params\": {
        \"task_id\": $1
    }
}"
echo

source userpass
curl --url "http://127.0.0.1:7783" --data "{
    \"mmrpc\":\"2.0\",
    \"userpass\":\"${userpass}\",
    \"method\":\"task::withdraw::init\",
    \"params\": {
        \"coin\":\"$1\",
        \"to\":\"$2\",
        \"amount\":\"$3\"
    }
    ,\"id\":0
}"


source userpass
curl --url "http://127.0.0.1:7783" --data "{
    \"mmrpc\":\"2.0\",
    \"userpass\":\"$userpass\",
    \"method\":\"task::withdraw::status\",
    \"params\": {
        \"task_id\":$1
    }
    ,\"id\":0
}"


source userpass
curl --url "http://127.0.0.1:7783" --data "{
    \"mmrpc\":\"2.0\",
    \"userpass\":\"$userpass\",
    \"method\":\"task::withdraw::cancel\",
    \"params\": {
        \"task_id\":$1
    }
    ,\"id\":0
}"
```

**Comment by sergeyboyko0791** [comment]
Thank you, looks right. Let's wait for `refactor-hw-api` is merged.
