### ISSUE TITLE
[future request] make docs more readable 

### ISSUE THREAD

**Issue by Canialon** [KomodoPlatform/developer-docs#427]
It is just a future request to make the docs easier to read. It is a lot of 
```
        \"coin\":\"$1\",
        \"to\":\"$2\",
        \"amount\":\"$3\"
```
moments 
and I guess it is not understandable for the user what $1, $2, and $3... mean. I do propose to make it like this 
```
        \"coin\":\"COIN_NAME\",
        \"to\":\"RECIPIENT_ADDRESS\",
        \"amount\":\"AMMOUNT_TO_SEND\"

       etc
```
or any other way where the user will get that he/she should change something in command and what exactly should input there.

__________________

Also, another moment I want to add `| jq` at the end of every command to get a readable response.

PS: If this future request makes sense I do want to take it.

**Comment by smk762** [comment]
Sounds good. Most of those were me from my bash scripts!
I'm not sure about the jq bit though - users would need to install it and windows is "special". In future we'll have multi-language examples so it will all be a bit different, but consistent variable names is a good enhancement.
