### ISSUE TITLE
Change ### Arguments/Response etc. to ####

### ISSUE THREAD

**Issue by siddhartha-crypto** [KomodoPlatform/developer-docs#44]
The ### hashtag registers in the search bar, whereas the #### hashtag does not. 

Need to change this mistake throughout documentation.

I fixed many of the immediately visible issues, but there are probably many more.

**Comment by gcharang** [comment]
What do you think about this:
 - https://community.algolia.com/docsearch/
 - https://vuepress.vuejs.org/default-theme-config/#algolia-search
It provides full-text search and free but its external

**Comment by siddhartha-crypto** [comment]
It's something to consider, but I don't think we need full text search. I would have to test it to know for sure.

I really like how the vuepress default search only searches headings. When I'm looking for a command while I'm working, it's nice to only see the specific commands as results and not have anything else. 

One of us just needs to go through each doc and replace each `### Arguments:` with `#### Arguments:`, and that's it. It's not complicated. I can do it soon, but it's not at the top of the priority list.

**Comment by gcharang** [comment]
![Screenshot from 2019-03-10 14-31-22](https://user-images.githubusercontent.com/21151592/54082828-399c7180-4341-11e9-92ed-71f1687141d4.png)
It's not that bad. Lots of open source projects use it for their Documentation. The above image is from https://vuejs.org/ Other projects like: babel,electron,react,bootstrap,yarn seem to use it

> I really like how the vuepress default search only searches headings. When I'm looking for a command while I'm working, it's nice to only see the specific commands as results and not have anything else.

Our docs have not only the API but other things too. If someone wanted to know about `wallet.dat` from our docs, the search bar that looks only for headers won't help.

Anyway it's your call.

**Comment by siddhartha-crypto** [comment]
Hmm, that is nice and orderly.

How about, after our next push to master, we give it a try on dev branch and see what we think. If we both like it after a week or two of testing, we can include it in the following push to master.

**Comment by gcharang** [comment]
Agreed

**Comment by siddhartha-crypto** [comment]
@gcharang 

did you want to work on this now?

**Comment by gcharang** [comment]
Let me finish the pending documentation tasks now, we can come back to this later
