### ISSUE TITLE
[future request] improve the command in docs for easier copy-paste

### ISSUE THREAD

**Issue by Canialon** [KomodoPlatform/developer-docs#448]
I want to suggest improving the command lines for easier copy-paste.

1. Delete the `#!/bin/bash source userpass` and `echo` lines. I guess the command which have this was taken from prepared scripts. But in docs, it's kind of useless, and it exists only in some places.
<img width="815" alt="image" src="https://user-images.githubusercontent.com/77272165/225285023-49c908a6-31c3-4fbb-ae63-8f19599acc6a.png">

2. Change all `YOUR_PASS` to `$userpass` for easier use without changing it manually. Actually, it is an $userpass setup in ADEX-API tutorial 
<img width="844" alt="image" src="https://user-images.githubusercontent.com/77272165/225286489-0a36dcf8-5c1b-4ecf-b8ef-0fcb08260fef.png">

3. Add a `copy` button at the top right corner to the code block

PS: I can try to do that:)

**Comment by gcharang** [comment]
can do this for the new docs

**Comment by smk762** [comment]
closing as completed in new docs site
