### ISSUE TITLE
User Request: Examples as drop down menus

### ISSUE THREAD

**Issue by siddhartha-crypto** [KomodoPlatform/developer-docs#5]
Request to make the examples an unexpanded drop down, to make reading and scanning the docs faster.

**Comment by siddhartha-komodo** [comment]
Feature previously submitted to Vuepress team:

https://github.com/vuejs/vuepress/issues/861

**Comment by gcharang** [comment]
might be useful:
https://vuetifyjs.com/en/components/expansion-panels
https://bootstrap-vue.js.org/docs/components/collapse/

**Comment by gcharang** [comment]
In the branch called `components` I have added a component that can hide the examples behind a button. Needs review and enhancement(style)

**Comment by gcharang** [comment]
@siddhartha-crypto this can be closed?

**Comment by siddhartha-crypto** [comment]
Yep, good work!
