### ISSUE TITLE
Possible deprecation warning

### ISSUE THREAD

**Issue by gcharang** [KomodoPlatform/developer-docs#7]
Seeing this after `yarn docs:dev`
```
TIP  override.styl has been split into 2 APIs, we recommend you upgrade to continue.
      See: https://v0.vuepress.vuejs.org/default-theme-config/#simple-css-override
```

**Comment by siddhartha-crypto** [comment]
I've upgraded to latest release of vuepress. It does not remove the warning, so I think we're okay. We're not using override.styl at this time anyway.
