### ISSUE TITLE
-gen -genproclimit=$(nproc) is not recommended

### ISSUE THREAD

**Issue by leto** [KomodoPlatform/developer-docs#73]
Alright informed me that various kinds of bugs can happen when using these params, as recommended by:

https://docs.komodoplatform.com/basic-docs/installations/creating-asset-chains.html#creating-a-new-asset-chain

It's much safer to recommend people to use `setgenerate` RPC after the daemon has started.

```
if you try to bootstrap a node by running ./komodod -ac_name=NAME -addnode=<IP> -gen -genproclimit=n
it might mine it's own block 1
and if you aren't bootstrapping
it might fork at the point where you were synced up until
```

**Comment by himu007** [comment]
for brand new chain mining with 1 CPU thread is more than enough `./komodod -ac_name=NAME -addnode=<IP> -gen -genproclimit=1`

**Comment by leto** [comment]
@himu007 I agree with you, 1 core is fine. But the main issue @Alrighttt is trying to point out is that there is some kind of race condition and using `setgenerate` after the daemon starts prevents that from happening, but using `-gen -genproclimit 1` could trigger the issue.

It's rare but I do believe I have hit this bug at least once with VRSC. I had laggy internet and using `-gen -genproclimit N` caused my node to mine it's own genesis block instead of sync properly from the network.

We should give people instructions that will work correctly all the time, not just most of the time.

**Comment by imylomylo** [comment]
Just to stick my big nose in....

Can we get some log print out or errors for the docs or dev
support/troubleshooting area, because ppl will find other doc sources for
creating chains and google the error.  It would be time saving to get
“expert system” sort of stuff published and for ppl to read the reason thru
search results onto our current doc/portal/info system.

**Comment by gcharang** [comment]
thanks for opening the issue @leto , this commit: https://github.com/KomodoPlatform/developer-docs/commit/43f6904c88fb8a8bcc018cfafdaa89b1f8af7bfe fixes the issue.

**Comment by leto** [comment]
@gcharang awesome, looks like the docs got additional info added too, nice!! :+1:
